### ISSUE TITLE
Proper shutdown handling?

### ISSUE THREAD

**Issue by alebon** [vn971/roboCup#1]
Hey, i have seen your post @ https://groups.google.com/forum/#!topic/liftweb/ANI-9KQYyn0
Thanks for sharing! But i have a question, i have more or less implemented one project the same way you shoed in this repository. Just one question, can you add a sample how to properly shutdown the application so this part is really called:

```
LiftRules.unloadHooks.append { () =>
        logger.info("roboCup actors shutdown")
        Core.system.shutdown()
}
```

I can not see the logging info in console. I have already tried ~reStop and Ctrl+C. Both just kill the application without a graceful shutdown.  

I heavily use this method to shutdown database connection pools, akka actors and so on...

Thanks a lot!

**Comment by vn971** [comment]
Ouch, why didn't I see this issue 4 months ago?.. I'll take a look.

**Comment by vn971** [comment]
Seems like you asked the question on the Mailing List, too (and it's answered there).

For history: the `sbt-revolver` plugin does not handle shutdown hooks properly, so there is no way to use a shutdown hook while in `reStart` (development) mode. https://github.com/spray/sbt-revolver/issues/20
